title:             Sarthak Agarwal
email:             sa5154@nyu.edu
description:       My Journney as a Data Scientist
author:            Sarthak Agarwal
baseurl:           ""
url:               "http://sarthak96agarwal.github.io"
theme: jekyll-theme-clean-blog
# Social Profiles
#twitter_username:  SBootstrap
github_username:   sarthak96agarwal
facebook_username: sarthak.agarwal.1422
linkedin_username: sarthak96agarwal

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
