title:             Sarthak Agarwal
email:             your-email@example.com
description:       Blog
author:            Sarthak Agarwal
baseurl:           ""
url:               "http://sarthak96agarwal.github.io"
theme: jekyll-theme-clean-blog
# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
